# Generated by Django 4.2 on 2024-04-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('schedule', models.CharField(max_length=200, verbose_name='График работы')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Кофейня',
                'verbose_name_plural': 'Кофейни',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('coffee_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_profile.coffeehouse', verbose_name='Кофейня')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объем/Количество')),
                ('unit', models.CharField(choices=[('ml', 'мл'), ('l', 'л'), ('g', 'гр'), ('kg', 'кг')], max_length=2, verbose_name='Единица измерения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Фото')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_profile.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
