# Generated by Django 4.2 on 2024-04-22 11:54

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffee_house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='URL')),
                ('coffee_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_house.coffeehouse', verbose_name='Кофейня')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='URL')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объем/Количество')),
                ('unit', models.CharField(choices=[('ml', 'мл'), ('l', 'л'), ('g', 'гр'), ('kg', 'кг')], max_length=2, verbose_name='Единица измерения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/menu_items/', verbose_name='Фото')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
